### ISSUE TITLE
readdir() attempted on invalid dirhandle

### ISSUE THREAD

**Issue by hafizmtalha** [sanger-pathogens/mlst_check#87] opened 2019-12-18 06:59 UTC
I m runnning the following command on my 2 samples and getting this error. Any help ???
get_sequence_type -s "Mycobacterium tuberclosis" -d 5 assembly.fasta ../S2202_/S2202_/assembly.fasta 
readdir() attempted on invalid dirhandle $dh at /usr/local/share/perl/5.26.1/Bio/MLST/SearchForFiles.pm line 26.
rewinddir() attempted on invalid dirhandle $dh at /usr/local/share/perl/5.26.1/Bio/MLST/SearchForFiles.pm line 31.
readdir() attempted on invalid dirhandle $dh at /usr/local/share/perl/5.26.1/Bio/MLST/SearchForFiles.pm line 32.

**Comment by magnusmanske** [comment] 2019-12-18 08:14
Duplicate of issue #65 , please see there for the solution

**Closed by magnusmanske** 2019-12-18 08:14 UTC
